version: '3'
services:

  backend:
    build:
      context: ./stockBackend  
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017/

  scraper:
    build:
      context: ./stockBackend  
      dockerfile: Dockerfile2
    ports:
      - "8002:8002"
    depends_on:
      - mongo
      - selenium
    environment:
      - MONGODB_URL=mongodb://mongo:27017/


  mongo:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - "27017:27017"

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    shm_size: "2g"
    environment:
      - SE_NODE_MAX_SESSIONS=5
  
